# Generated by Django 3.2.7 on 2021-11-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnosModel',
            fields=[
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=100)),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=100)),
                ('usuarioDni', models.CharField(db_column='dni', max_length=8, null=True)),
                ('usuarioCodigo', models.CharField(db_column='codigo', max_length=9, null=True)),
                ('usuarioCalificacion', models.CharField(db_column='calificacion', max_length=5, null=True)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='FotoModel',
            fields=[
                ('fotoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('fotoUrl', models.CharField(db_column='url', max_length=280)),
                ('alumno', models.ForeignKey(db_column='alumno_id', on_delete=django.db.models.deletion.PROTECT, related_name='alumnoFoto', to='iec.alumnosmodel')),
            ],
            options={
                'db_table': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=50)),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=50, verbose_name='Apellido del usuario')),
                ('usuarioCorreo', models.EmailField(db_column='email', max_length=50, unique=True)),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'anonimo'), (3, 'idat')], db_column='tipo', default=2)),
                ('password', models.TextField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
